### ISSUE TITLE
Suggestion to fix autolayout crashes

### ISSUE THREAD

**Issue by jonasman** [allaboutapps/A3ParallaxScrollView#5]
replace the layoutsubvies with this:

``` objective-c
  - (void)layoutSubviews{
        [super layoutSubviews];


    for (UIView *v in self.subviews) {
        // get acceleration
        CGPoint accelecration = [self accelerationForView:v];

        // move the view
        [v.layer setAffineTransform:CGAffineTransformMakeTranslation(self.contentOffset.x*(1.0f-accelecration.x), self.contentOffset.y*(1.0f-accelecration.y))];
         }
    }
```

I can do a pull request if you want?

**Comment by BotiKis** [comment]
Can you tell me why it is crashing in first place?
I can't test it right now...

The fix is OK, but i want to understand that first.

**Comment by jonasman** [comment]
The crash is related to autolayout and view.transform

you can read more here: http://stackoverflow.com/questions/12943107/how-do-i-adjust-the-anchor-point-of-a-calayer-when-auto-layout-is-being-used/14105757#14105757

According to the solution applying a transform to the view.layer is ok but not to the view itself.

when you apply a transform in the view, it will kick a layoutSubviews and crash.

**Comment by BotiKis** [comment]
Wow, i've luckily avoided this problem a couple of times.
Still good to know.  

So even if it's _fixed_ with iOS 8 i would appreciate a fix. If you make a pull request i merge it immediately.

Thank you!

**Comment by jonasman** [comment]
I will do it! 
Ios8 still crashes.

Enviado do meu iPhone

No dia 02/10/2014, às 16:56, Botond Kis notifications@github.com escreveu:

**Comment by jonasman** [comment]
https://github.com/allaboutapps/A3ParallaxScrollView/pull/6

**Comment by pfryerda** [comment]
Note that this crash still occurs on the CocoaPods version of A3ParallaxScrollView.  Might want to do an update.

**Comment by BotiKis** [comment]
Thank you, totally forgot about that! Done.
